[project]
name = "simple-wav-player"
version = "1.0.0"
description = "Simple wav file player"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "comtypes>=1.4.11",
    "pyaudio>=0.2.14",
    "pycaw>=20240210",
]
